name: pcd
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.8
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - blosc=1.21.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-blosc2=2.4.2
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cffi=1.15.1
  - cfitsio=4.1.0
  - charls=2.3.4
  - click=8.0.4
  - cloudpickle=2.2.0
  - colorama=0.4.5
  - contourpy=1.0.5
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2022.9.2
  - dataclasses=0.8
  - dav1d=1.0.0
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.1.1
  - expat=2.4.9
  - ffmpeg=4.4.2
  - flask=2.1.3
  - flit-core=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.37.4
  - freeglut=3.2.2
  - freetype=2.12.1
  - fsspec=2022.8.2
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.74.0
  - glib-tools=2.74.0
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - icu=70.1
  - imagecodecs=2022.9.26
  - imageio=2.22.0
  - importlib-metadata=4.11.4
  - importlib_resources=5.10.0
  - intel-openmp=2022.1.0
  - ipykernel=6.16.0
  - ipython=8.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.2
  - itsdangerous=2.0.1
  - jasper=2.0.33
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.3.5
  - jupyter_console=6.4.4
  - jupyter_core=4.11.1
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.3
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=4.0.0
  - libaec=1.0.6
  - libavif=0.10.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=7.85.0
  - libdeflate=1.14
  - libffi=3.4.2
  - libglib=2.74.0
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libogg=1.3.4
  - libopencv=4.6.0
  - libpng=1.6.38
  - libprotobuf=3.21.7
  - libsodium=1.0.18
  - libsqlite=3.39.4
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.12
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.1
  - matplotlib=3.6.0
  - matplotlib-base=3.6.0
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2022.1.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbclient=0.7.0
  - nbconvert=7.2.1
  - nbconvert-core=7.2.1
  - nbconvert-pandoc=7.2.1
  - nbformat=5.6.1
  - nest-asyncio=1.5.6
  - networkx=2.8.7
  - notebook=6.4.12
  - numpy=1.23.3
  - opencv=4.6.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.3.0
  - pcre2=10.37
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pkgutil-resolve-name=1.3.10
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.31
  - prompt_toolkit=3.0.31
  - psutil=5.9.2
  - pthread-stubs=0.4
  - pure_eval=0.2.2
  - py-opencv=4.6.0
  - pycparser=2.21
  - pygments=2.13.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.1
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.9
  - pywavelets=1.3.0
  - pywin32=303
  - pywinpty=2.0.8
  - pyyaml=6.0
  - pyzmq=24.0.1
  - qt-main=5.15.6
  - qtconsole=5.3.2
  - qtconsole-base=5.3.2
  - qtpy=2.2.1
  - scikit-image=0.19.3
  - scipy=1.9.1
  - send2trash=1.8.0
  - setuptools=65.4.1
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - soupsieve=2.3.2.post1
  - sqlite=3.39.4
  - stack_data=0.5.1
  - svt-av1=1.2.1
  - tbb=2021.6.0
  - terminado=0.16.0
  - tifffile=2022.8.12
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - traitlets=5.4.0
  - typing_extensions=4.4.0
  - tzdata=2022d
  - ucrt=10.0.20348.0
  - unicodedata2=14.0.0
  - vc=14.2
  - vs2015_runtime=14.29.30139
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.3
  - wheel=0.37.1
  - widgetsnbextension=4.0.3
  - winpty=0.4.3
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.9.0
  - zlib=1.2.12
  - zlib-ng=2.0.6
  - zstd=1.5.2
